name: Publish Chrome Extension

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to publish (e.g., 1.0.1)'
                required: true

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Setup Node.js
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run linter
              run: npm run lint

            - name: Type check
              run: npm run ts

            - name: Build extension
              run: npm run build

            - name: Get version
              id: version
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    VERSION="${{ github.event.inputs.version }}"
                  else
                    VERSION="${GITHUB_REF#refs/tags/v}"
                  fi
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "Publishing version: $VERSION"

            - name: Upload to Chrome Web Store
              uses: PlasmoHQ/bpp@b2ac7d3106cbb14a3cdc05b57795d6e9e778def5 # v3
              with:
                  keys: ${{ secrets.BPP_KEYS }}
                  artifact: viceroy.zip
                  verbose: true

            - name: Create GitHub Release
              uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5 # v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: viceroy.zip
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
